Make bin/elixir POSIX compliant
We use Shellcheck as a linter
https://github.com/koalaman/shellcheck

It passes all checks except SC016,
which I intentionally left for redability.

$ shellcheck -e SC2016,SC2086 bin/elixir

diff --git a/bin/elixir b/bin/elixir
--- a/bin/elixir
+++ b/bin/elixir
@@ -69,8 +69,17 @@ ERL=""
 
 # Stores erl arguments preserving spaces/quotes (mimics an array)
 erl () {
-  eval "E$E=\$1"
-  E=$(($E + 1))
+  eval "E${E}=\$1"
+  E=$((E + 1))
+}
+
+# Checks if a line starts with char
+# starts_with "$LINE", "$CHAR"
+starts_with () {
+case $1 in
+  "$2"*) true;;
+  *) false;;
+esac
 }
 
 ERL_EXEC="erl"
@@ -132,7 +141,7 @@ while [ $I -le $LENGTH ]; do
         ;;
     --sname|--name)
         S=2
-        erl $(echo $1 | cut -c 2-)
+        erl "$(echo "$1" | cut -c 2-)"
         erl "$2"
         ;;
     --erl-config)
@@ -159,23 +168,19 @@ while [ $I -le $LENGTH ]; do
     --pipe-to)
         S=3
         RUN_ERL_PIPE="$2"
-        case "$RUN_ERL_PIPE" in
-          -*) echo "--pipe-to : PIPEDIR cannot be a switch" >&2 && exit 1;;
-          *);;
-        esac
-
         RUN_ERL_LOG="$3"
-        case "$RUN_ERL_LOG" in
-          -*) echo "--pipe-to : LOGDIR cannot be a switch" >&2 && exit 1;;
-          *);;
-        esac
+        if [ "$(starts_with "$RUN_ERL_PIPE" "-")" ]; then
+          echo "--pipe-to : PIPEDIR cannot be a switch" >&2 && exit 1
+        elif [ "$(starts_with "$RUN_ERL_LOG" "-")" ]; then
+          echo "--pipe-to : LOGDIR cannot be a switch" >&2 && exit 1
+        fi
         ;;
     --werl)
         if [ "$OS" = "Windows_NT" ]; then ERL_EXEC="werl"; fi
         ;;
     *)
         while [ $I -le $LENGTH ]; do
-          I=$(($I + 1))
+          I=$((I + 1))
           set -- "$@" "$1"
           shift
         done
@@ -183,19 +188,23 @@ while [ $I -le $LENGTH ]; do
         ;;
   esac
 
-  I=$(($I + $S))
+  I=$((I + S))
   shift $S
 done
 
-I=$(($E - 1))
+I=$((E - 1))
 while [ $I -ge 0 ]; do
   eval "VAL=\$E$I"
   set -- "$VAL" "$@"
-  I=$(($I - 1))
+  I=$((I - 1))
 done
 
 SELF=$(readlink_f "$0")
 SCRIPT_PATH=$(dirname "$SELF")
+
+# $OSTYPE is not POSIX compliant
+# https://github.com/pstadler/metrics.sh/blob/master/lib/utils/os.sh
+if [ -z "$OSTYPE" ]; then OSTYPE=$(uname | tr '[:upper:]' '[:lower:]'); fi
 
 if [ "$OSTYPE" = "cygwin" ]; then SCRIPT_PATH=$(cygpath -m "$SCRIPT_PATH"); fi
 if [ "$MODE" != "iex" ]; then ERL="-noshell -s elixir start_cli $ERL"; fi
@@ -210,7 +219,8 @@ set -- "$ERTS_BIN$ERL_EXEC" -pa "$SCRIPT_PATH"/../lib/*/ebin $ELIXIR_ERL_OPTIONS
 if [ -n "$RUN_ERL_PIPE" ]; then
   ESCAPED=""
   for PART in "$@"; do
-    ESCAPED=""$ESCAPED" $(echo "$PART" | sed 's/[^a-zA-Z0-9_\-\/]/\\&/g')"
+    PART_ESCAPED="$(echo "$PART" | sed 's/[^a-zA-Z0-9_\-\/]/\\&/g')"
+    ESCAPED="$(printf "%s %s" "$ESCAPED" "$PART_ESCAPED")"
   done
   mkdir -p "$RUN_ERL_PIPE"
   mkdir -p "$RUN_ERL_LOG"
